sudo: false
language: go

# Build matrix : Linux X All supported architectures
go:
- 1.5
- 1.6
- tip
env:
- GOOS=linux GOARCH=386
- GOOS=linux GOARCH=amd64
- GOOS=linux GOARCH=arm
- GOOS=linux GOARCH=arm64

# Build and Test commands in sequence
before_install:
- export GORACE="halt_on_error=1"
- export GO15VENDOREXPERIMENT=1
- go get -u github.com/Masterminds/glide
- go get -u github.com/golang/lint/golint
install:
- glide install
script:
- go vet
- golint --set_exit_status
- go build -v -race
- go test -v -race