sudo: false
language: go

# Build matrix : Linux X All supported architectures
go: 1.6
env:
- GOOS=linux GOARCH=386
- GOOS=linux GOARCH=amd64
- GOOS=linux GOARCH=arm
- GOOS=linux GOARCH=arm64

before_install:
- go get -u github.com/Masterminds/glide
install:
- glide install
script:
- go build -v
- go test -v

